### ISSUE TITLE
Nezávislost na verzi Nette v aplikaci.

### ISSUE THREAD

**Issue by PetrP** [Clevis/HttpPHPUnit#1]
Tedy že by knihovna rovnou obsahovala [minifikovaný NetteX](https://github.com/nette/apigen/tree/master/libs/NetteX)

**Comment by vojtech-dobes** [comment]
Do toho jsem se pustil u Realgangu, protože mi to dělalo problémy, pokusím se co nejdřív to hodit do nějaké větve. (sorry za ten reopen, github na to má pěkně blbě umístěné tlačítko :) )
