### ISSUE TITLE
Readme or howto

### ISSUE THREAD

**Issue by Vrtak-CZ** [Clevis/HttpPHPUnit#10]
cucim jak puk ze uz je to PUB ale chtelo by to nejaky howto jak to nainstalovat / pouzivat.

**Comment by rdpanek** [comment]
Hele, já to mám nějak sepsaný, ale schytal jsem děsnou krytyku - jak mile na mě bude mít autor trochu času - upravíme a určitě publikneme.

Jinak defakto stačí stáhnout., /tests/run.php a používat :-)

**Comment by JanTvrdik** [comment]
Zkus si stáhnout http://www.uloz.to/12516822/tests-rar

**Comment by MartyIX** [comment]
Tuto verzi od JanTvrdik se mi podařilo rozběhnout na Nette 2 final, stačilo jen přidat do souborů TemplateFactory.php a StructureRenderer.php funkci:

``` php
public function templatePrepareFilters($template)
{
        $template->registerFilter(new \Nette\Latte\Engine());
}
```

Diky, vypada to skvele!
