### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by Vrtak-CZ** [Clevis/HttpPHPUnit#11]
Poslední dobou přemýšlím jak bych to mohl používat a došel jsem k tomu že to určitě nechci mít součástí kódu aplikace a víc by se hodilo mít to jako samostatnou aplikaci. Kde s v konfiguraci budu definovat jednotlivé aplikace (Jméno a cesta k testům).

**Comment by rdpanek** [comment]
Přemýšlel jsi si HttpPHPUnit instalnout do aplikace jako submodul? Technicky vzato je  to součástí tvé aplikace pokud si to nainicalizujes jako submodul.

**Comment by Vrtak-CZ** [comment]
Technicky vzato to nechci jako součást své aplikace. Je to nástroj. A chci to jako nástroj používat.

**Comment by Vrtak-CZ** [comment]
any news?

**Comment by PetrP** [comment]
Co tě nutí mít to jako součást aplikace?

I když já si myslím, že je to úžitečné, stejně jako mít součástí aplikace (git repozitáře) konkrétní knihovny které potřebuješ k testování (phpunit apod.) Protože testy nemusí fungouvat z každou verzí phpunitu který má někdo nainstalované v pearu.

Ještě lepší než mít součástí repositáře by bylo mít zavislosti nastavené přes Composer.

**Comment by Vrtak-CZ** [comment]
Pro mě je to nepovinný nástroj. A tak bych to chtěl jako nástroj používat. Ideálně tedy jako aplikaci kde vyplním cestu k projektu. Nastavím cestu k phpunit.xml a je. Pro mě je to aktuálně nepoužitelné protože to vyžaduje Nette v projektu a já tam mám Nellu.
