### ISSUE TITLE
include_path directive is overwritten by HttpPHPUnit

### ISSUE THREAD

**Issue by MartyIX** [Clevis/HttpPHPUnit#12]
https://github.com/Clevisaci/HttpPHPUnit/blob/master/HttpPHPUnit/Main/Main.php#L56 -- This commands overwrites include_path. The problem is that the directive may contain path to PEAR directory.

Proposed patch:

```
set_include_path($phpUnitDir . PATH_SEPARATOR . get_include_path());
```

**Comment by PetrP** [comment]
Thanks for reporting bug. Sorry for delay.
