### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Vrtak-CZ** [Clevis/HttpPHPUnit#17]
please make installable via composer

**Comment by VitekJezek** [comment]
please make pull request : P

**Comment by Vrtak-CZ** [comment]
If I had time for making pull req. I send it but I don't have time for do that. Because it's not only make composer.json file but need makes lot's of code changes (eg. #16).

**Comment by PetrP** [comment]
Yesterday I rewrote almost  whole code. One of the new features will be composer support. Please wait a few days. :-)

**Comment by PetrP** [comment]
I need do some stuff before I put it on packagist.

So meanwhile you can add custom repository to your composer.json. At least I think it is possible. I'm not a composer guru :-)

**Comment by MartyIX** [comment]
Is it necessary to have Nette in libs/Nette folder? It would be great to add a dependency to composer.json.
