### ISSUE TITLE
ResultPrinter_getTestInfo_Test: Failed asserting

### ISSUE THREAD

**Issue by rdpanek** [Clevis/HttpPHPUnit#7]
Na MAC OSX se projevuje při spuštění testů pro HTTPPHPUnit a hláškou:

Failed asserting that string:<h2Failures</h2><div class="error"><h3><span class="state">Error</span> in <a href="?test=/ResultPrinter_getTestInfo_Test.php::DataProvider+with+data+set+%22%22">ResultPrinter_getTestInfo :: DataProvider</a> <small class="editor"><a href="editor://open/?file=%2FVolumes%2Fhtdocs%2FHttpPHPUnit%2Ftests%2Fcases%2FResultPrinter%2FResultPrinter_getTestInfo_Test.php&amp;line=15">open in editor</a></small><br><small><small> with data set "" (1, 2, '&lt;b&gt;3&lt;/b&gt;')</small></small></h3><p>Exception: (no message)</p></div>> contains "<a href="?test=\ResultPrinter_getTestInfo_Test.php::DataProvider+with+data+set+%22%22">ResultPrinter_getTestInfo :: DataProvider</a>".

**Comment by PetrP** [comment]
problem je v rozdilnych koncich radku win vs unix.
Dne 5.11.2011 12:23 "Radim Daniel" <
reply@reply.github.com>
napsal(a):

**Comment by PetrP** [comment]
Tím commitem jsi to opravil pro unix a rozbyl pro windows.

**Comment by tomasfejfar** [comment]
Co používat env-specific PHP_EOL (\n resp. \r\n) a DIRECTORY_SEPARATOR (/ resp )
