### ISSUE TITLE
Doba behu

### ISSUE THREAD

**Issue by VitekJezek** [Clevis/HttpPHPUnit#8]
Nesla by zobrazovat doba behu testu? Treba takove seleniove testy nebezi uplne rychle (a ted moc nevim, jak dlouho s nimi muzu pocitat).

//cc @PetrP @JanTvrdik

**Comment by JanTvrdik** [comment]
Co je to doba běhu "testu" / "testů"?

**Comment by VitekJezek** [comment]
Proste jak dlouho bezi (pokud se jeste testuje) ci bezeli (az se dotestuje ; )

**Comment by PetrP** [comment]
To jak dlouho vše běželo se ± dozvíš z nette debug baru.

Jak dlouho testy poběží se ale nedá dopředu říct. Nevím jak každý test
dlouho poběží. Ukládat info z minulého běhu se mi zdá dost divoké. A každé
spuštění může být dost jiné.

Proč je ta informace tak důležitá, nestačí ti vlastní odhad?
